### ISSUE TITLE
Maxlength of comment in blueprint

### ISSUE THREAD

**Issue by gerritvanaaken** [Addpixel/KirbyComments#14]
I wouldn’t set the maxlength in the default blueprint. I configured the maxlength in the config, but I do not want to copy the blueprint from the plugin folder to my site/blueprints folder just to change this small detail.

**Comment by florianpircher** [comment]
Fixed in v1.2.1: <https://github.com/Addpixel/KirbyComments/releases/tag/1.2.1>
