### ISSUE TITLE
Get paid

### ISSUE THREAD

**Issue by jenstornell** [Addpixel/KirbyComments#19]
This plugin seems to be quite big. Have you considered to take a fee for it? If it works well, I think it could be worth about 50 EUR for 1 single domain.

You could use the same license as Kirby. Then it would not be a locked in plugin. I think https://creativemarket.com/imchris/457176-Kirby-Comments is a **bad** example where we can't read or test the code or test the pluigin first. I think a plugin like this could need a month of testing before buying.

If you don't want to get paid, what is your motivation? You have over 200 commits. =)

**Comment by florianpircher** [comment]
Firstly: thank you for your encouragement! It does mean a lot to me hearing that my code’s value is estimated at 50 €/domain. (Or 20 cent/commit, hm…)

Still, I don’t like the idea of taking a fee for Kirby Comments. Here are some reasons in an unordered list:

- If people had to pay for Kirby Comments, fewer people would be using Kirby Comments and that would make me sad :(
- Once people payed for software, they feel entitled to force me to make changes to it, effectively making it their own software. That would make me sad :(
- Another thing to consider is support. While I believe offering official support is a necessity when selling software online, I don’t want to offer any official support. I just can’t see myself answering more than three support tickets per day.
- Dealing with licenses and refunds is no fun.
- Any list with an even number of items looks odd.

I appreciate your suggestion and the generosity of your proposal, but getting payed for doing something is never as fun as doing it for the fun of it. That said, if you do use Kirby Comments in a commercial setting and are therefore worried about *Spirit of Ecstasy* on your new Rolls-Royce, be assured that every [donation](https://www.paypal.me/florianpircher/) will be deeply appreciated.

**Comment by jenstornell** [comment]
To be honest, I've not tried your plugin yet, only tested it on your demo. However I need the comments feature on a few sites soon (within a year).

One of the reasons is Google Adword policy:
https://www.en.advertisercommunity.com/t5/Articles/Google-AdWords-Bridge-Page-policy-How-to-avoid-this-policy/ba-p/65516#

>Having user reviews, commenting feature and clickable rating gives users an opportunity to post their views and opinion about the products/services offered on the site and thus improve their overall experience on the site.

If I have comments or reviews Google will probably accept me of using Adwords on my affiliate sites.

Except for Google, it's of course of value for users of the site as well and that should really be the main reason.

I don't get paid for my plugins and I've created about 50 of them ( and deleted about 10). The reasons are the same as yours so I completely understand your point of view.

If your plugin works as good as it seems by your demo/readme I could donate for sure. Just don't expect it soon. What I plan now often comes in about 6 month. If I find issues during testing you will see me adding issues again. =)
