### ISSUE TITLE
Adding custom fields

### ISSUE THREAD

**Issue by wottpal** [Addpixel/KirbyComments#23]
Hi, 
first thank you for your amazing work. 🎉

Is there an straightforward way for adding a custom field (like a Twitter handle) to comments. Or do I have to manually modify the plugins-core?

Dennis

**Comment by florianpircher** [comment]
Unfortunately custom fields are currently not supported. I am planing to offer the following interface for creating custom fields:

A custom field can be created in Kirbys config.php and **must** include:

- a name for the KirbyText key
- an HTTP POST name
- an `isRequired` flag

Additionally it **can** include:

- a validation function which may throw errors in the 4xx domain
- a sanitation function for improving values (e.g. "example.org" to "http\://example.org")

Comments about the above interface are welcome.

**Comment by wottpal** [comment]
Sound super cool! 💯
Maybe an additional option for an HTML5 form-validation pattern could be useful.

**Comment by florianpircher** [comment]
The plugin is independent of the markup you are using. Kirby Comments includes some snippets for a quick start, but you can create any HTML code you want. Have a look at the [custom markup](https://github.com/Addpixel/KirbyComments#custom-markup) section for more information.

**Comment by florianpircher** [comment]
[Version 1.5.0](https://github.com/Addpixel/KirbyComments/releases/tag/1.5.0) is live and on master! For more on custom fields have a look at

- the [Custom Fields Guide](https://github.com/Addpixel/KirbyComments#custom-fields) and
- the [Custom Fields API Documentation](https://github.com/Addpixel/KirbyComments#type--commentsfieldtype).
