### ISSUE TITLE
Minor Blueprint Issue

### ISSUE THREAD

**Issue by wottpal** [Addpixel/KirbyComments#24]
It didn't display the filled in website-url in the panel for me. I've tried to change it by renaming the `url` field to `website` in `blueprints/comment.yml` and voilà it was filled in after a reload. Might be a bug?

Dennis

**Comment by florianpircher** [comment]
Thank you for catching this mistake! It’s fixed in d550841da68de769c8b543579e16a8ee0841e38d, which is currently on develop and will be part of the next release.
