### ISSUE TITLE
Comment-Numbering

### ISSUE THREAD

**Issue by wottpal** [Addpixel/KirbyComments#25]
Hey Florian, 
lets assume I have 2 comments on my page (`comment-1` and `comment-2`) and *delete* `comment-1` in the panel for whatever reason. If I go to my page and try to write a new comment that doesn't work because it tries to create `comment-2` which already exists. I assume you are checking for the subpage-count or so to determine the next number but maybe you should do a check after that if the desired comment-number exists already. And increment it until a not already used one is found :)

Thanks for your fast replies,
Dennis

OT: Ich studiere übrigens Informatik in Jena, nur mal so als Funfact am Rande :D Habe gelesen du studierst das ebenfalls ;)

**Comment by florianpircher** [comment]
Thank you for your testing! This behavior has been fixed in version [1.4.2](https://github.com/Addpixel/KirbyComments/releases/tag/1.4.2).

OT: Gutes Studium in Jena!
