### ISSUE TITLE
Moderate comments

### ISSUE THREAD

**Issue by jenstornell** [Addpixel/KirbyComments#29]
It would be nice to have the comments as pending and accepting them in the panel. Close this issue if it already works like this. Thanks.

**Comment by florianpircher** [comment]
This is in the works (#1), but quite difficult to write with the documented Kirby API. Sending messages between the panel and the plugin over a secure connection is (to my knowledge) not documented in the Kirby docs.

I will close this because it’s the same idea as in #1.

**Comment by jenstornell** [comment]
Be aware that Kirby 3 will change a lot so maybe not work your ass off with the panel stuff. I'm not allowed to talk about it and I'm not sure if you are in there or not but here are some info:

https://getkirby.com/next
