### ISSUE TITLE
Feature request : Kirby extension registry

### ISSUE THREAD

**Issue by malvese** [Addpixel/KirbyComments#3]
It would be nice if this plugin used the [Kirby extension registry](https://getkirby.com/docs/developer-guide/plugins/registry), so it could be installed and updated easily as a submodule or with the Kirby CLI, without having to move files around.

**Comment by florianpircher** [comment]
This looks like an obvious next step. I’m going to implement this, so expect a new release of this plugin in 1–3 weeks supporting Kirby’s extension registry. The only thing I am currently unsure of, is how to test whether a plugin is fully supported by the extension registry before releasing it.

**Comment by florianpircher** [comment]
[Version 1.1.3](https://github.com/Addpixel/KirbyComments/releases/tag/1.1.3) of this plugin was just released which adds support for the Kirby extension registry.
