### ISSUE TITLE
Email and url optional fields?

### ISSUE THREAD

**Issue by jenstornell** [Addpixel/KirbyComments#36]
I do not require email and url in my comments because my users probably don't want to give this information.

Anyway, would it be a good idea to have them optional? I can remove them from the template but I guess they will still be in the blueprint and content as empty values?

**Comment by florianpircher** [comment]
Email- and website-address are part of the plugin core, which is why they are stored even if empty.

> Anyway, would it be a good idea to have them optional?

Both of them are optional. You can even make `name` optional by setting the `comments.form.name.required` config to `false`.

**Comment by jenstornell** [comment]
I meant that it would be optional to not save them in the content if they are empty.

Anyway, if you implement that pre hook, then it could be used to remove unneeded fields as well, keeping it clean in cases like this.

**Comment by florianpircher** [comment]
In version [1.5.1](https://github.com/Addpixel/KirbyComments/releases/tag/1.5.1) unused fields are no longer stored in the page.
