### ISSUE TITLE
Paginated comments

### ISSUE THREAD

**Issue by jenstornell** [Addpixel/KirbyComments#37]
What will happend when we have 300 comments on a page. I guess they will all be listed on the same page. Are there any plans to somehow paginate them?

**Comment by florianpircher** [comment]
Duplicate: #16 

Check out [Custom Markup: Comments List](https://github.com/Addpixel/KirbyComments#custom-markup-comments-list) for a guid on implementing a custom list. If you want to, you can also use [`$comments->toArray()`](https://github.com/Addpixel/KirbyComments#comments-toarray--comment) to access the array directly.
