### ISSUE TITLE
Case of some file names after upgrade

### ISSUE THREAD

**Issue by malvese** [Addpixel/KirbyComments#39]
I had a strange issue after I updated to 1.5 with the Kirby CLI, and I'm not sure if it is an issue with KirbyComments or the CLI.

Two already existing files kept their case (all lowercase instead of capital case):
- `plugin/comments.php` instead of `plugin/Comments.php`
- `plugin/comment.php` instead of `plugin/Comment.php`

It didn't matter on the local site on my Mac, because the file system is case insensitive. But once deployed it broke on the server. It took me a while to find why the site crashed, but renaming the files with a capital "C" fixed it.

**Comment by florianpircher** [comment]
> Two already existing files kept their case

Does that mean that the capitalization of some other files changed?

**Comment by malvese** [comment]
Not sure about other files, I only noticed those two because it didn't work when they were `include`ed.

Not sure I was clear: all files in the `plugin` folder initially had their names in lowercase. Starting with 1.4.1 they are now capitalized, but most have also been renamed (like `comments-email.php` to `CommentsEmail.php`). Only the two I listed still have the same name (except they are now capitalized).

What I think happened is when I updated KirbyComments, the content of the files were updated but since Macs have a case insensitive file system, the name was considered correct and they remained in all lowercase.

The more I think about it, it's probably more a Git or Kirby CLI issue than one in your plugin.

**Comment by florianpircher** [comment]
I did rename the plugin files with 1.4.1, but at the same time I changed the `include` statements in the main plugin file ([see diff between 1.4.0 and 1.4.1](https://github.com/Addpixel/KirbyComments/compare/1.4.0...1.4.1#diff-1)). I will investigate this issue and close it for now.

**Comment by malvese** [comment]
An images is worth a thousand words, this is what my `plugin` folder looked like *after* I updated with the Kirby CLI:

<img width="194" alt="case" src="https://user-images.githubusercontent.com/193492/34939156-18e408a4-f9eb-11e7-9079-3237b921bb6e.png">

The names of the first two filed were not capitalized during the update. The includes then shouldn't have worked, but they did locally because macOS is case insensitive.
