### ISSUE TITLE
`dirname` options don't seem to work

### ISSUE THREAD

**Issue by malvese** [Addpixel/KirbyComments#4]
I tried to configure KirbyComments with dirnames in French:

```
c::set('comments.comments-page.dirname', 'commentaires');
```

When I try this on a post without any coment yet, the first level is created (`commentaires`) but no comment is actually saved inside of it.

On the other hand `
c::set('comments.comment-page.dirname', 'commentaire');` alone seems to work and each comment folder gets a name like `1-commentaire-1`.

**Comment by florianpircher** [comment]
At first glance, it seams like the only mistake I’ve made was to use the fixed string value `"comments"` on [this line](https://github.com/Addpixel/KirbyComments/blob/master/comments.php#L154). I’m going to double check that, test it and in case of success publish a new release. Thank you for reporting this issue! 😃

**Comment by malvese** [comment]
Nice, I think you nailed it!
A side issue is that it is not always clear what the option does.
For example `comments-page.title` is said to "Name of the template of a comments page", when it actually seems to set the name of the _blueprint_.
I know blueprints and template are tied, but in this plugin the default templates are _snippets_ so it was not obvious for me.

**Comment by florianpircher** [comment]
Version [1.1.4](https://github.com/Addpixel/KirbyComments/releases/tag/1.1.4) fixes this bug.
