### ISSUE TITLE
Updating parent page when posting comment

### ISSUE THREAD

**Issue by chrisgwynne** [Addpixel/KirbyComments#41]
Is there any way to update a field in the parent page when posting a comment?

**Comment by florianpircher** [comment]
Yes, you can use a [hook](https://github.com/Addpixel/KirbyComments#hooks) to run your logic for specific events, e.g. [`did-save-comment`](https://github.com/Addpixel/KirbyComments#did-save-commentcomments--comments-comment--comment-commentpage--page).

**Comment by chrisgwynne** [comment]
`c::set('comments.hooks.did-save-comment', function ($comments, $comment) {
  $page = $page->$parent()->update(array('lastupdated'        => 'd-m-Y H:i:s'));
  return false;
});`

I'm not the best with this unfortunately florian, keeps throwing up errors.

**Comment by florianpircher** [comment]
`$page` is undefined in config.php. You can access the page object using the `$comment` variable:

```php
c::set('comments.hooks.did-save-comment', function ($comments, $comment, $commentPage) {
  try {
    $comment->page()->update(...);
  } catch (Exception $e) {
    // do something with the exception
    echo $e->getMessage();
  }
});
```

Some other notes:

- `$page->$parent()` will never work, the dollar-sign ($) is used only when accessing a variable, not methods and properties: `$page->parent()`.
- I think `'lastupdated' => 'd-m-Y H:i:s'` should be `'lastupdated' => date('d-m-Y H:i:s')`.
- You don’t need to return anything in the `did-save-comment` hook, as the return value is ignored.

**Comment by chrisgwynne** [comment]
Florian, this works perfectly, thank you so much! :)
