### ISSUE TITLE
max-character-count prevents old comments from showing; breaks comment form

### ISSUE THREAD

**Issue by samnabi** [Addpixel/KirbyComments#9]
If you have an existing comment whose `text` field is 900 characters long, it will be fine because the default `max-character-count` is 1000.

However, if you decide to change the `max-character-count` in the future to 500, the existing comment will not show up. It gets caught by the [Comment constructor](https://github.com/Addpixel/KirbyComments/blob/b984cc6c2d46fa1fb9b11493e71c67e81b7750d1/plugin/comment.php#L83) and returns an error.

Now, this is a problem for writing new comments too. Since the existing comment doesn't make it through to the `$comments` array in the template, the numbering is off for any new comments. The submission form counts the wrong number of existing comments, and therefore tries to submit a comment with an ID that already exists. The form will silently fail, and never show the preview.

I haven't tested this extensively, but I think the main problem here is with the Comment constructor function. The validation code shouldn't apply retroactively to existing comments.

**Comment by florianpircher** [comment]
Thank you for finding this bug! By making the constructor more save I made it incompatible with possible feature settings. While some options can not be changed once the plugin is in use, I agree that this should not be some of them.
